### PR TITLE
Bugfix: Checkout is broken

### PR DESCRIPTION
**Pull request by svenauhagen**
Once an order is approved by Mondu the state of the order is not set to processing and the cart also needs to be cleared.

Otherwise the order will time out after a while and gets cancelled.

## Description

The checkout is broken.

Fixes # (issue)

## Release information

Please **specify** p/m/M/- for patch/minor/major/none
Release:
Please **specify** only ticket id's separated with commas (F.E. BNPL-21, BNPL-22)
Tickets:
## Type of change

Please **delete** options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have checked my code and corrected any misspellings
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by arthurmmoreira** [comment]
Hi Sven,
Thanks for your pull request!
Changing the order's status to processing is made when we can also confirm the order on our end. The Mondu API sends a request to the [webhooks controller](https://github.com/mondu-ai/bnpl-checkout-woocommerce/blob/main/src/Mondu/Mondu/Controllers/WebhooksController.php#L148) and the status is changed.
However, I will be glad to include the empty cart part in our codebase.

**Comment by svenauhagen** [comment]
Hi @arthurmmoreira,

I looked through the code and can see what you are saying but this call never happens.
All orders stay in payment pending in our store and after a while timeout to cancelled.

How is this mechanism supposed to work?
Is the Mondu Server accessing our server or is the Wordpress code supposed to call the API?
How is the calling convention for this new mechanism.

Best
Sven

**Comment by arthurmmoreira** [comment]
Hi @svenauhagen,

Due to the new workflow (hosted checkout), the order flow is divided into two steps: authorizing and confirming. If you successfully complete the checkout, the order is in the authorized state. As a final step, our widget should call [this action](https://github.com/mondu-ai/bnpl-checkout-woocommerce/blob/main/src/Mondu/Mondu/Controllers/OrdersController.php#L34-L51) defined in the order controller to calls Mondu API and change the order state to confirmed.
If the order is confirmed on the Mondu side, the Mondu Server submits a webhook call to WordPress to change the WooCommerce order state to processing.

Best,
Arthur

**Comment by svenauhagen** [comment]
Hi @arthurmmoreira so this call never arrives at our server. We are behind cloudflare and WAF and something is blocking it. There is a number of other things that can go wrong if your server needs to call the woocommerce server. The only reliable way is if the woocommerce server tries to pull the information from the mondo server. Is there any reason this is not possible?

**Comment by arthurmmoreira** [comment]
Hi @svenauhagen,

I checked internally and the webhook calling part to your server is actually working (I checked with a few old orders and had a 200 response). The only problem I saw with this new workflow is that the confirm endpoint never reached the Mondu server (using the action mentioned above).

Yes, it is possible to retrieve order data from Mondu via an API call. This happens whenever someone accesses the WooCommerce admin area and opens a Mondu order. I can add an update on the WooCommerce order during this process. Do you think this could solve the problem you are having?

Best,
Arthur

**Comment by svenauhagen** [comment]
@arthurmmoreira I think I am getting to the problem.
So we use WPML and our URLs are based on the language:
www.voleatech.de/de
www.voleatech.de/en
and so on.

If you use get_site_url for the callback it give you the base url www.voleatech.de
This seems to work for the users browser checkout but the callback gets a 302 to redirect it to www.voleatech.de/de our default language.
What seems to work is:
$success_url = home_url() . '?rest_route=/mondu/v1/orders/confirm&external_reference_id=' . $order->get_order_number() . '&return_url=' . urlencode( $this->get_return_url( $order ) ) ;

You can reproduce it by enabling WPML and set the settings like in my screenshot.
Go to WPML -> Languages and set the Site and Language URL Format.

Screenshot 2023-08-01 at 13 35 04

**Comment by arthurmmoreira** [comment]
Hi @svenauhagen,

We discussed it internally and will approach this issue in a different way.

For a quick fix, we updated your webhooks addresses manually to include the missing `/de` path and avoid the redirect. Can you please do another round of tests with the updated version and check if it works? Also, when updating the plugin to the newer version, please do NOT re-register the webhooks.

Best,
Arthur

**Comment by svenauhagen** [comment]
Hi @arthurmmoreira,

I updated the plugin in my production environment but when I validate my credentials I do get forbidden now.
Can you have a look on your end?

I have not reregistered the webhook to keep it working.

**Comment by arthurmmoreira** [comment]
Hi @svenauhagen,

I just checked the logs and you are trying to validate your production key in the demo environment. Can you change it to production, save it and try again?

Best,
Arthur

**Comment by svenauhagen** [comment]
Hi @arthurmmoreira,

it was already on production but the object cache had the old settings.
Sorry about that.
I will try and test it and get back to you.

Best
Sven

**Comment by svenauhagen** [comment]
Hi @arthurmmoreira,

so it works on my staging site but I am getting other errors now in production.

Error placing an order. Please try again.

So I am not sure what is going on now.
Any way we can schedule a debug session?

Best
Sven

**Comment by arthurmmoreira** [comment]
Hi @svenauhagen,

I'm talking with the team to schedule it.

Best,
Arthur

**Comment by dviana19** [comment]
solved by
- https://github.com/mondu-ai/bnpl-checkout-woocommerce/pull/94
- https://github.com/mondu-ai/bnpl-checkout-woocommerce/pull/95

**Pull request closed without merging**
